eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        preferIpAddress: true
server:
    port: 4001

# springdoc:
#     api-docs:
#         path: /api-docs

spring:
    application:
        name: AUTH-DEPARTMENT
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/authdb
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            properties:
                spring:
                    json:
                        add:
                            type:
                                headers: false
        topic:
            auth: authtopic
    liquibase:
        enabled: true
    main:
        allow-bean-definition-overriding: true
